version: '3'
services:
  buildkite_agent:
    image: buildkite/agent:3
    volumes:
      # - /var/lib/buildkite/builds:/var/lib/buildkite/builds
      # - /usr/local/bin/buildkite-agent:/usr/local/bin/buildkite-agent
      - /var/run/docker.sock:/var/run/docker.sock
    # environment:
    #   BUILDKITE_BUILD_PATHX: /var/lib/buildkite/builds
    command: [ "start", "--token", "$BUILDKITE_AGENT_TOKEN" ]
# volumes:
#   bka-builds:
#   bka-agent:
